GET http://localhost:5003


###
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}


###
// This below shows that middleware can accept JSON tokens from past server instances since it is encoded with JWT secret key but it still returns the id from the previous instance so if the previous instance token had an id of 2 and you try to run it on the new instance which only has 1 registered user, then you get an error. Essentially, it's not checking if the token is from this instance.
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "bilgamesh@gmail.com",
    "password": "223123123"
}


###
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}


### Fetch all todos GET /TODOS (protected)
GET http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MjA0MzE0LCJleHAiOjE3MzgyOTA3MTR9.hrmO23u75FbMnQhDDVc8v7vuVWsSy1feYKghgwD2WB0


### Creates a new todo POST /TODOS (protected)
POST http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MjA0MzE0LCJleHAiOjE3MzgyOTA3MTR9.hrmO23u75FbMnQhDDVc8v7vuVWsSy1feYKghgwD2WB0
Content-Type: application/json

{
    "task": "Finish coding the projects"
}


### Update a todo PUT /TODOS/:ID (protected)
PUT http://localhost:5003/todos/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM4MjA0MzE0LCJleHAiOjE3MzgyOTA3MTR9.hrmO23u75FbMnQhDDVc8v7vuVWsSy1feYKghgwD2WB0
Content-Type: application/json

{
    "completed": 1
}